version: "3.9"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.dev
    depends_on:
      - db
  db:
    image: postgres:15-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.dev.db

volumes:
  postgres_data:
