version: "3.9"

services:
  web:
    build:
      context: ./app
      dockerfile: Prod.Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./env/.env.prod
    depends_on:
      - db
  db:
    image: postgres:15-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
