# Generated by Django 4.2 on 2023-05-16 13:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('order', models.PositiveSmallIntegerField(verbose_name='порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subregions', to='core.region', verbose_name='входит в')),
            ],
            options={
                'verbose_name': 'регион',
                'verbose_name_plural': 'регионы',
                'ordering': ('order', 'name'),
            },
        ),
    ]
