# Generated by Django 4.2 on 2023-05-17 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, verbose_name='краткое наименование')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='полное наименование')),
                ('numeric_code', models.CharField(max_length=10, verbose_name='цифровой код')),
                ('alpha2_code', models.CharField(max_length=10, verbose_name='альфа-2')),
                ('alpha3_code', models.CharField(max_length=10, verbose_name='альфа-3')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='core.region', verbose_name='регион')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
                'ordering': ('numeric_code', 'short_name', 'alpha2_code', 'alpha3_code'),
            },
        ),
    ]
